Update bin/detect

diff --git a/bin/detect b/bin/detect
--- a/bin/detect
+++ b/bin/detect
@@ -1,9 +1,12 @@
 #!/bin/sh
 
-if [ ! -z $(grep "com.android.application" "build.gradle") ]; then
-  echo "-----> com.android.application plugin detected in build.gradle"
+
+if [ -f $1/build/gradle ]; then
+  echo "-----> build.gradle detected"
+  grep -q "com.android.application" build.gradle; [ $? -eq 0 ] && echo "yes" || echo "-----> Could not find 'com.android.application' in your build.gradle! Please ensure your project is properly configured. This plugin is generally aplied to the root build.gradle"
+#  echo "-----> com.android.application plugin detected in build.gradle"
   exit 0
 else
-  echo "-----> Could not find 'com.android.application' in your build.gradle! Please ensure your project is properly configured. This plugin is generally aplied to the root build.gradle"
+  echo "-----> Could not find your root build.gradle file."
   exit 1
 fi
