Update bin/detect, bin.bak/detect

diff --git a/bin/detect b/bin/detect
--- a/bin/detect
+++ b/bin/detect
@@ -1,10 +1,12 @@
-#!/usr/bin/env bash
-# bin/use <build-dir>
+#!/bin/sh
 
 grep -q "com.android.application" build.gradle > $FILES
 cat $FILES
 
-echo "no" && exit 1
-
-
-
+if [ -e $1/build.gradle ]; then
+  grep -q "com.android.application" build.gradle; [ $? -eq 0 ] && echo "===> com.android.application plugin detected in build.gradle" || echo "$FAIL"
+  exit 0
+else
+  echo "Not Android"
+  exit 1
+fi
