Update bin/detect

diff --git a/bin/detect b/bin/detect
--- a/bin/detect
+++ b/bin/detect
@@ -1,12 +1,5 @@
 #!/bin/sh
 
-grep -q "com.android.application" build.gradle > $FILES
-cat $FILES
 
-if [ -e $1/build.gradle ]; then
-  grep -q "com.android.application" build.gradle; [ $? -eq 0 ] && echo "===> com.android.application plugin detected in build.gradle" || echo "$FAIL"
-  exit 0
-else
-  echo "Not Android"
-  exit 1
-fi
+grep -q "com.android.application" build.gradle; [ $? -eq 0 ] && echo "===> com.android.application plugin detected in build.gradle" exit 0 || echo "$FAIL"
+exit 1
