Update bin/detect

diff --git a/bin/detect b/bin/detect
--- a/bin/detect
+++ b/bin/detect
@@ -2,12 +2,13 @@
 
 if [ -z ${CI_PROJECT_DIR+x} ]; then echo "CI_PROJECT_DIR is unset"; else echo "CI_PROJECT_DIR is set to '$CI_PROJECT_DIR'"; fi
 
+env
+
 # this pack is valid for apps with a hello.txt in the root
-if [ -f $1/hello.txt ]; then
-  echo "HelloFramework"
-  exit 0
+if [ -f $1/gradlew ]; then
+  echo "ANDROID!" && exit 0
 else
-  exit 1
+  (>&2 echo "Could not find an 'AndroidManifest' file... Please check that it exists and is commited to Git. The usual location for this file is /app/src/main/AndroidManifest.xml")
 fi
 
 #if [ -f "${CI_PROJECT_DIR}" ]; then
