Update bin/detect

diff --git a/bin/detect b/bin/detect
--- a/bin/detect
+++ b/bin/detect
@@ -1,9 +1,9 @@
 #!/bin/sh
 
 # this pack is valid for apps with a hello.txt in the root
-if [ -f $1/app/src/main/AndroidManifest.xml ]; then
+if [ -f $1/app ]; then
   echo "Android Manifest Found!"
   exit 0
 else
-  exit 1
+  (>&2 echo "Could not find an 'AndroidManifest' file... Please check that it exists and is commited to Git. The usual location for this file is /app/src/main/AndroidManifest.xml")
 fi
