Update bin/detect

diff --git a/bin/detect b/bin/detect
--- a/bin/detect
+++ b/bin/detect
@@ -2,11 +2,14 @@
 FILE=$1/build.gradle
 
 grep -q "com.android.application" build.gradle; [ $? -eq 0 ] && echo "===> com.android.application plugin detected in build.gradle"   || echo "$FAIL"
-grep -q "com.android.application" build.fail; [ $? -eq 0 ] && echo "===> com.android.application plugin detected in build.gradle"   || echo "$FAIL"
+grep -q "com.android.application" build.*; [ $? -eq 0 ] && echo "===> com.android.application plugin detected in build.gradle"   || echo "$FAIL"
+if [ -e build.gradle ]; then echo "ok" else echo "ko" ; fi
+if [ -e $1/build.gradle ]; then echo "ok" else echo "ko" ; fi
 
-ls $1
+ls $1/
 
-if [ -s $1/build.gradle ]; then
+test -f 
+if [ -s $PWD/build.gradle ]; then
   echo "Android"
   exit 0
 else
