Update bin.bak/detect, bin/detect, bin/compile

diff --git a/bin/detect b/bin/detect
--- a/bin/detect
+++ b/bin/detect
@@ -1,3 +1,9 @@
 #!/bin/sh
 
-exit 0
+if [ -e build.gradle ]; then
+  grep -q "com.android.application" build.gradle; [ $? -eq 0 ] && echo "===> com.android.application plugin detected in build.gradle" || echo "$FAIL"
+  exit 0
+else
+  echo "Not Android"
+  exit 1
+fi
