Update bin/detect

diff --git a/bin/detect b/bin/detect
--- a/bin/detect
+++ b/bin/detect
@@ -1,9 +1,13 @@
 #!/bin/sh
 
+manifest=$1/app/src/main/AndroidManifest.xml
+
 # this pack is valid for apps with a hello.txt in the root
-if [ -f $1/app ]; then
+if [ -f $1/,gradlew ]; then
   echo "Android Manifest Found!"
   exit 0
 else
-  (>&2 echo "Could not find an 'AndroidManifest' file... Please check that it exists and is commited to Git. The usual location for this file is /app/src/main/AndroidManifest.xml")
+  echo "Android Manifest Found!"
+  exit 1
+#  (>&2 echo "Could not find an 'AndroidManifest' file... Please check that it exists and is commited to Git. The usual location for this file is /app/src/main/AndroidManifest.xml")
 fi
