Update bin/detect

diff --git a/bin/detect b/bin/detect
--- a/bin/detect
+++ b/bin/detect
@@ -1,19 +1,12 @@
-#!/bin/sh
+#!/usr/bin/env bash
+set -eo pipefail
 
-ls
+FAIL="===> Could not find 'com.android.application' in your build.gradle! Please ensure your project is properly configured. This plugin is generally aplied to the root build.gradle"
 
-FILE=build.gradle
-if [ -f "$FILE" ]; then
-    echo "$FILE exists."
-else 
-    echo "$FILE does not exist."
-fi
-
-if [ -f build.gradle ]; then
-  echo "===> build.gradle detected"
-  grep -q "com.android.application" build.gradle; [ $? -eq 0 ] && echo "===> com.android.application plugin detected in build.gradle" || echo "===> Could not find 'com.android.application' in your build.gradle! Please ensure your project is properly configured. This plugin is generally aplied to the root build.gradle"
-  exit 0
-else
+if [[ ! -f build.gradle ]]; then
   echo "===> Could not find your root build.gradle file."
   exit 1
+else 
+  echo "===> build.gradle detected"
+  grep -q "com.android.application" build.gradle; [ $? -eq 0 ] && echo "===> com.android.application plugin detected in build.gradle" || echo "$FAIL"
 fi
