Update .gitlab-ci.yml, bin/detect

diff --git a/bin/detect b/bin/detect
--- a/bin/detect
+++ b/bin/detect
@@ -1,7 +1,10 @@
 #!/bin/sh
-FILE=build.gradle
+FILE=$1/build.gradle
 
-if [ -s $FILE ]; then
+grep -q "com.android.application" build.gradle; [ $? -eq 0 ] && echo "===> com.android.application plugin detected in build.gradle"   || echo "$FAIL"
+grep -q "com.android.application" build.fail; [ $? -eq 0 ] && echo "===> com.android.application plugin detected in build.gradle"   || echo "$FAIL"
+
+if [ -s $1/build.gradle ]; then
   echo "Android"
   exit 0
 else
