Update bin/detect, bin.bak/detect

diff --git a/bin.bak/detect b/bin.bak/detect
--- a/bin.bak/detect
+++ b/bin.bak/detect
@@ -14,3 +14,13 @@ if [ -f "${ROOT_DIR}/app/src/main/AndroidManifest.xml" ]; then
 else 
   (>&2 echo "Could not find an 'AndroidManifest' file... Please check that it exists and is commited to Git. The usual location for this file is /app/src/main/AndroidManifest.xml")
 fi
+
+
+
+if [[ ! -f build.gradle ]]; then
+  echo "===> Could not find your root build.gradle file."
+  exit 1
+else 
+  echo "===> build.gradle detected"
+  grep -q "com.android.application" build.gradle; [ $? -eq 0 ] && echo "===> com.android.application plugin detected in build.gradle"  && exit 0 || echo "$FAIL" &&  exit 1
+fi
